apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: microservices
type: Opaque
data:
  # ตัวอย่างการเก็บข้อมูลลับ เช่น รหัสผ่าน (เข้ารหัส base64)
  RABBITMQ_PASSWORD: YWRtaW5fcGFzc3dvcmQ= # 'admin_password' encoded in base64
  MONGODB_PASSWORD: bW9uZ29fcGFzcw== # 'mongo_pass' encoded in base64
  SECRET_KEY: c2VjcmV0X2tleV92YWx1ZQ== # 'secret_key_value' encoded in base64
